### ISSUE TITLE
Broken eval with scalars

### ISSUE THREAD

**Issue by boldar99** [discopy/discopy#216]
When you evaluate a simple diagram that has a scalar too, you get an error.

Example:
```py
from discopy.quantum import Ket, scalar, H, CX, Rz, Id, qubit
import tensornetwork as tn

d = scalar(2) @ CX
c = tn.contractors.auto
```
Output
```
Traceback (most recent call last):
  File "/opt/homebrew/Caskroom/miniforge/base/envs/py39/lib/python3.9/site-packages/IPython/core/interactiveshell.py", line 3508, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-2-c92aa3968986>", line 1, in <module>
    runfile('/Users/boldi/PycharmProjects/discopy/testt.py', wdir='/Users/boldi/PycharmProjects/discopy')
  File "/Users/boldi/Applications/PyCharm Professional Edition.app/Contents/plugins/python/helpers/pydev/_pydev_bundle/pydev_umd.py", line 198, in runfile
    pydev_imports.execfile(filename, global_vars, local_vars)  # execute the script
  File "/Users/boldi/Applications/PyCharm Professional Edition.app/Contents/plugins/python/helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "/Users/boldi/PycharmProjects/discopy/testt.py", line 6, in <module>
    print(d.eval(contractor=c))
  File "/Users/boldi/PycharmProjects/discopy/discopy/quantum/circuit.py", line 292, in eval
    array = contractor(*a).tensor
  File "/opt/homebrew/Caskroom/miniforge/base/envs/py39/lib/python3.9/site-packages/tensornetwork/contractors/opt_einsum_paths/path_contractors.py", line 245, in auto
    return optimal(nodes, output_edge_order, memory_limit, ignore_edge_order)
  File "/opt/homebrew/Caskroom/miniforge/base/envs/py39/lib/python3.9/site-packages/tensornetwork/contractors/opt_einsum_paths/path_contractors.py", line 126, in optimal
    return base(nodes, alg, output_edge_order, ignore_edge_order)
  File "/opt/homebrew/Caskroom/miniforge/base/envs/py39/lib/python3.9/site-packages/tensornetwork/contractors/opt_einsum_paths/path_contractors.py", line 87, in base
    for a, b in path:
ValueError: not enough values to unpack (expected 2, got 1)
```

**Comment by y-richie-y** [comment]
Seems to me like a `tensornetwork` bug:

This errs
```python
import numpy as np
import tensornetwork as tn

a = tn.Node(np.array(2))
b = tn.Node(np.array(3))

tn.contractors.auto([a, b])
```

This errs

```python
import numpy as np
import tensornetwork as tn

a = tn.Node(np.array(2))
b = tn.Node(np.array([1, 2]))
c = tn.Node(np.array([3, 4]))

tn.connect(b[0], c[0])
tn.contractors.auto([a, b, c])
```

But this works.
```python
import numpy as np
import tensornetwork as tn

a = tn.Node(np.array([1, 2]))
b = tn.Node(np.array([3, 4]))
c = tn.Node(np.array([1, 2]))
d = tn.Node(np.array([3, 4]))

tn.connect(a[0], b[0])
tn.connect(c[0], d[0])
tn.contractors.auto([a, b, c, d])
```

**Comment by y-richie-y** [comment]
https://optimized-einsum.readthedocs.io/en/stable/path_finding.html#format-of-the-path

I've raised a fix in google/TensorNetwork:
https://github.com/google/TensorNetwork/pull/974

**Comment by toumix** [comment]
Looks like there hasn't been any review on their repo for almost two years...

![Screenshot 2023-09-05 at 10 50 46](https://github.com/discopy/discopy/assets/6673255/1591b8f4-2198-4354-9589-961d9cddd884)

Is there an easy fix we can do on our side, e.g. adding a special case for scalars somewhere? Otherwise we may have to fork our own version of tensornetwork.
